#!/bin/bash
if ps aux | grep -v -e "grep" -e "bash" | grep "conky" >/dev/null;then
  echo 'exit';
  exit;
else

  sleep 5 &

  conky -c ~/.conky/info.conkyrc &
  #conky -c ~/.conky/logs.conkyrc &
  conky -c ~/.conky/network.conkyrc &
  conky -c ~/.conky/weather.conkyrc &
  conky -c ~/.conky/sys.conkyrc
fi
